version: '3'

services:
  nginx-proxy:
    build: ./infra/nginx
    image: proxy-network
    ports:
      - 80:80
      - 443:443
    
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./.htpasswd:/etc/nginx/htpasswd
      # - ./vhost.d:/etc/nginx/vhost.d

networks:
  default:
    name: my_proxy_network