version: '3'

services:
  nginx-proxy:
    build: ./infra/nginx
    image: proxy-network
    ports:
      - 80:80
      - 443:443
    
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      # - ./vhost.d:/etc/nginx/vhost.d

  db:
    image: postgres
    container_name: my_database
    volumes:
      - ./infra/database/data:/var/lib/postgresql/data
      - ./infra/database/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - ${DB_PORT}:5432

networks:
  default:
    name: my_proxy_network