version: '3'

services:
  nginx-proxy:
    build: ./infra/nginx
    container_name: nginx_proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - my_proxy_network
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./.htpasswd:/etc/nginx/htpasswd
      - ./vhost.d:/etc/nginx/vhost.d
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    environment:
      - NGINX_PROXY_CONTAINER=nginx_proxy
    networks:
      - my_proxy_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html

networks:
  my_proxy_network:
    name: my_proxy_network